### ISSUE TITLE
isucon13

### ISSUE THREAD

**Issue by Doarakko** [Doarakko/isucon13#37]
# Todo

## 事前準備

- [x] 空のプライベートリポジトリを作成
    - チームで出る場合はメンバー全員にアクセス権限を付与

## 開始

- [ ] マニュアルを読む
- [ ] アプリケーションマニュアルを読む
- [x] setup
    - [x] SSH 接続可能な状態にする
    - [x] GitHub を用いて以下の変更を反映できるようにする
        - アプリケーション
        - `nginx.conf`
        - `mysqld.cnf`
    - [x] 事前準備したファイルを使用可能な状態にする
    - [x] 各種ツールをインストールする
- [x] アプリケーションの構成を把握する
    - サーバ構成
    - インスタンスサイズ
- [ ] 使用されている OS・ミドルウェアとそのバージョンを確認する
    - MySQL
    - nginx
- [x] 初回ベンチマークを実行する
    -　各種ログ出力を有効にする前のスコアを確認するためにこのタイミングで実行する
- [ ] 各種ログ出力を有効にする
    - [x] nginx
    - [x] MySQL スロークエリログ
    - [ ] New Relic
    - [ ] pprof
- [x] ベンチマークを再実行する
- [x] テーブル構成を把握する
- [x] データの UPDATE・INSERT・DELETE が行われている箇所を把握する
- [ ] 方針を立てる

### アプリケーション

- [ ] New Relic の設定を削除
- [ ] pprof の設定を削除

### MySQL

- [ ] スロークエリログの出力を停止

### nginx

- [ ] ログ出力を停止

**Comment by Doarakko** [comment]
insert
- livestreams
- livestream_tags
- livestream_viewers_history
- livecomments
- livecomment_reports
- ng_words
- reactions
- icons
- users
- themes

update
- reservation_slots

delete
- livecomments
- icons
- livestream_viewers_history
